### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by bit4bit** [driftyco/ionic-cli#1034]
hi,

when i run **ionic run browser -l**
throws

~~~
Setup Live Reload
server start error: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.checkForDocumentRoot (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:248:27)
    at Object.start (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:487:16)
    at /usr/local/lib/node_modules/ionic/lib/utils/cordova.js:257:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
There was an error serving your Ionic application for run server start error: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.checkForDocumentRoot (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:248:27)
    at Object.start (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:487:16)
    at /usr/local/lib/node_modules/ionic/lib/utils/cordova.js:257:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
undefined
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
~~~

the same for **ionic run android -l**

**ionic version: 2.0.0-beta.29**

**Comment by DBnR1** [comment]
I started receiving the same error after running `npm update -g` to get rid of another error.

My Ionic version is also 2.0.0-beta.29

**Comment by skaman** [comment]
Same here, the problem appeared after cli and ionic lib update. Tried a new project from scratch and same error.
Ionic serve with the browser work right. Ionic with livereload on ios or android throw in this error.

**Comment by skaman** [comment]
Ok, little workaround that temporary solve this issue for me.
Inside the /usr/local/lib/node_modules/ionic/lib/utils/cordova.js the setupLiveReload is called with a baseDir equal to undefined.

To let it start i hardcoded the path of my project in that setupLiveReload function. This fix the issue but the livereload still not reload if i change my code. But at least i can run the app inside the emulator with some usefull log.

Hope for some hint or update from ionic team.

```
function setupLiveReload(argv, baseDir) {
  log.info(('Setup Live Reload').green.bold);

  baseDir = '/path/of/my/project';
  var project = Project.load(baseDir);
  var options = _.extend(Serve.loadSettings(argv, project), {
```

**Comment by ValentinBlokhin** [comment]
I had the same issue, but I just set
`baseDir = ''`
and it is working now.

**Comment by jthoms1** [comment]
Thank you for helping identify this issue!  I have resolved the problem and it will be fixed in the next CLI release which should be pushed in the next day or two.  Thanks for being patient, and I apologize for any inconvenience this might have caused.

**Comment by leizard** [comment]
thank you @jthoms1. I have the exact issue and hope it will be fixed soon.

**Comment by jthoms1** [comment]
This issue should be fixed now in release beta.30.   https://github.com/driftyco/ionic-cli/blob/v2/CHANGELOG.md

**Comment by johnlowvale** [comment]
im using CLI 2 beta, but it still doesn't build:

```
D:\abi\tests\myApp>ionic run android
Running command: d:\progs\free\nodejs-links\node.exe D:\abi\tests\myApp\hooks\af
ter_prepare\010_add_platform_class.js D:\abi\tests\myApp


add to body class: platform-android

Error: Path must be a string. Received undefined
```

ionic info:

```
D:\abi\tests\myApp>ionic info

Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS:
Node Version: v5.9.1
```

**Comment by johnlowvale** [comment]
i found out why, i have to set ANDROID_HOME environment variable, 

but this matter is described in Apache Cordova Project, not in Ionic Project

**Comment by Arlem** [comment]
This occurred to me when I changed some <resource-file> names without reflecting the update on plugin.xml.

**Comment by JoshWilliams92** [comment]
I'm having the same issue on my laptop when trying to upgrade to RC 3.0. It works on my computer but not on my laptop.
