### ISSUE TITLE
ionic setup sass - setup is not a valid task

### ISSUE THREAD

**Issue by roblouie** [driftyco/ionic-cli#1245]
The documentation says that to use sass automatically to run `ionic setup sass`, however that just results in the error "setup is not a valid task" and a list of available tasks.

**Comment by CheetahDev** [comment]
setup**s**?

**Comment by roblouie** [comment]
@CheetahDev That was just a typo on my part, I have corrected it.  The command is still invalid, despite what the docs say.

**Comment by jgw96** [comment]
Hello! Would you mind updating your ionic cli install by running `sudo npm install -g ionic@beta` and then testing again? Thanks for using Ionic!

**Comment by okonon** [comment]
@jgw96 Same issue here...
```
Cordova CLI: 6.3.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by roblouie** [comment]
@jgw96 I'm on Windows, but I did update to the latest, I'm on v2.0.0-beta.36.

I still receive the same error setup is not a valid task

**Comment by okonon** [comment]
@jgw96 This issue is related to #1250 I think...

**Comment by NeckbreakerPascal** [comment]
another problem with this issue is, that for now the scss files are not automatically create new css files when I change something. Even not when I build the app etc.

Is there a workaround for that?

**Comment by meskatjahan** [comment]
I am also, facing the problem ... 

    setup is not a valid task

**Comment by meskatjahan** [comment]
same problem... 
    
    ionic setup sass - setup is not a valid task

**Comment by jgw96** [comment]
Hello! With the release of the 2.0 version of the ionic cli this should be fixed! Thanks for using Ionic!

**Comment by Xinxin-Ma** [comment]
Hello! I am working on ionic 2 and I still have this problem. Is it fixed?

**Comment by kumbhanialex111** [comment]
browser is not a valid task

**Comment by guilhermefelipesilva** [comment]
Resolution prevision?

**Comment by boulakar** [comment]
Hi can you help me plz i have thise error 

https://www.screencast.com/t/c5lOc2eNBdK
