### ISSUE TITLE
After upgrade to 2.0.0, SASS build is not working

### ISSUE THREAD

**Issue by sebrojas14** [driftyco/ionic-cli#1276]

**Comment by PTthe13** [comment]
I'm having the same problem. After updating Ionic CLI to v2, can't seem to build my sass (scss) files.

**Comment by Untilo** [comment]
Same here. 
Gulp Sass triggered manually does the trick. 
Something to do with the "watch" part ?

**Comment by AaronMorse** [comment]
Solution in #1250 worked for me

**Comment by PTthe13** [comment]
@AaronMorse thanks for that. Worked for me...

**Comment by sagivf** [comment]
This works for me but I don't get the live reload on `ionic emulate ios` just have to add the watch task in gulpfile. Added this pull request - https://github.com/driftyco/ionic-cli/pull/1299

**Comment by HriBB** [comment]
Can confirm this. It works with `ionic@1.7.2`. This should be working without a workaround.

**Comment by sebrojas14** [comment]
What happen with this? How is possible to launch a main version like this?

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by sebrojas14** [comment]
Is still happening, I had to manually add this line to my gulpfile.js

gulp.task('serve:before', ['default','watch']);
