### ISSUE TITLE
ionic-cli V3  cordova:plugin add with variables

### ISSUE THREAD

**Issue by hugoblanc** [driftyco/ionic-cli#1974]
ionic cordova:plugin add plugin with variable is not working on  "version": "3.0.0-beta.4"

Exemple: `cordova plugin add cordova-plugin-facebook4 --save  --variable APP_ID="Value" --variable APP_NAME="Value"`  work fine

If we do same with ionic syntaxe:
`ionic cordova:plugin add cordova-plugin-facebook4 --variable APP_ID="Value" --variable APP_NAME="Value"` 
then: 
```
[ERROR] An error occurred while running the above command (exit code 1):
        Error: Variable(s) missing (use: --variable APP_ID=value --variable APP_NAME=value).
```

**Comment by jthoms1** [comment]
Seems like this is an undocumented feature of the CLI. https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#cordova-plugin-command

I have verified that it is a bug and I should have a fix out by tomorrow afternoon.

**Comment by jthoms1** [comment]
This issue is fixed with commit 0aade803d2d1a4db2607fe88ffa3a67cf502f946. This fix should be released tomorrow.

**Comment by obermoserkitz** [comment]
Since it's not released yet, how do we profit from this fix?

**Comment by simetin** [comment]
As it been release ? I've updated to the 3.0.0 Beta 4 a couple of days ago and it's still not working.

**Comment by jthoms1** [comment]
This has been fixed and is in beta5 which released last week.  Please update to beta5.

**Comment by simetin** [comment]
I get the same results with beta5
![screen shot 2017-04-03 at 2 16 25 pm](https://cloud.githubusercontent.com/assets/7005663/24624051/9a5305b6-1878-11e7-802a-06fe3ff51e77.png)
