### ISSUE TITLE
3.0.0-beta.4 can´t download templates behind proxy

### ISSUE THREAD

**Issue by elTorres** [driftyco/ionic-cli#2024]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta.4

#### Short description of the problem:

ionic-cli can´t download templates behind proxy. I have no problem with 2.2 version.

#### What behavior are you expecting?

Download templates using nodejs proxy configuration

**Steps to reproduce:**
1. ionic start blank blank --v2 --skip-npm

**Post the output of `ionic info` below please**

    Cordova CLI: 6.5.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.3.0
    Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

```
D:\tmp>ionic start blank blank --v2 --skip-npm
✔ Creating directory D:\tmp\blank - done!
✖ Downloading 'blank' starter template - failed!
{ Error
    at ClientRequest.<anonymous> (D:\nodejs\pnpm-global\node_modules\.registry.npmjs.org\node-fetch\1.6.3\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'FetchError',
  message: 'request to https://github.com/driftyco/ionic2-app-base/archive/master.tar.gz failed, reason: connect ECONNREFUSED 192.30.253.113:443',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }

D:\tmp>
```

**Comment by alexgv99** [comment]
Any news about that?

**Comment by jthoms1** [comment]
Can you verify did this issue not appear for the v2 CLI?  The templates are being downloaded directly from github.

**Comment by jvitor83** [comment]
@jthoms1
I am experiencing the same issue here.
This issue doesn't happen on CLI v2!

**Comment by jthoms1** [comment]
I will look into this further not sure how I can reproduce, but I will research.

**Comment by alexgv99** [comment]
I was trying to understand the code (https://github.com/driftyco/ionic-cli/blob/v3/packages/ionic/src/commands/start.ts#L199) and how to set proxy... actually, you can use something like the following code, when http_proxy and https_proxys environment variables, or .npmrc (proxy and https_proxy) are set:
```
fetch('https://www.google.com',{ agent:new HttpsProxyAgent('http://127.0.0.1:8580')}).then(function(res){
    ...
})
``` code from https://github.com/bitinn/node-fetch/issues/79#issuecomment-184594701

**Comment by dwieeb** [comment]
@alexgv99 @jvitor83 @elTorres This will be fixed in the next release of CLI v3 beta. We now look at the same environment variables as npm (`http_proxy`, etc) as well as `IONIC_HTTP_PROXY` in case somebody needs to route traffic through a different proxy for just ionic traffic.

**Comment by frostbytedata** [comment]
What is the workaround until then? I am unable to start a new Ionic project no matter what proxy config I use.

**Comment by dwieeb** [comment]
@frostbytedata This has been fixed for quite a while in the v3 beta.

**Comment by frostbytedata** [comment]
Ok I'm running 3.0.0rc2 and I still have this issue. Is that the absolute latest, or do I have some other network issue at play here? Thanks so much for your help, really love this framework and community.

**Comment by dwieeb** [comment]
@frostbytedata Hmm, that's odd. Have you set the `HTTP_PROXY` environment variable?

**Comment by frostbytedata** [comment]
@dwieeb Yes Dan I did have those set. However it seems the issue resolved itself after deleting, cleaning npm cache, and then reinstalling the Ionic CLI. 

Thanks again for your help, I don't know how you guys manage to help idiots like me all day without throwing in the towel. It is appreciated here.

**Comment by dwieeb** [comment]
@frostbytedata Actually, I might be the idiot here! The CLI won't be able to proxy for global commands yet: https://github.com/driftyco/ionic-cli/issues/2234

**Comment by captainhook99999** [comment]
I ran into this problem today and after a whole day's struggling, I fixed it.
Probably you are behind a proxy server.

**First, make sure you can use "git" properly.**
Because IONIC use git to download starter templates.
```
git config --global http.sslverify false
git config --global http.sslcainfo "path to your certificate file *.crt"
```
(You may also set "user.name" and "user.email" values if you have a git hub account.)

**Second, let "npm" not to check ssl certificate**
```
npm config set strict-ssl false
npm config set registry "http://registry.npmjs.org/" --global
```

**Third, make "Node.js" not to check ssl certificate.**
On Windows Powershell, type
```
$env:NODE_TLS_REJECT_UNAUTHORIZED ="0"
```
then try again.
```
ionic start blank blank
```
Good Luck.

**Comment by dwieeb** [comment]
@captainhook99999 

The Ionic CLI does not use git to download starters unless you specify a git url. 

Turning off SSL verification anywhere could not be discouraged more. If you are getting SSL issues, you likely need to update your system to get new CA certificates installed OR you are behind a proxy and your system or proxy is improperly configured. Talk with your proxy server administrator.

**Comment by ragul13** [comment]
Hello All,

im getting an error while starting a new project  

command -ionic start myapp tabs

error
:downloading and extracting tabs starter - failed!
error: connect ETIMEDOUT 54.230.0.136.443
    at object.exports._errnoException      <util.js:1020:11>
    at exports._expectionWithHostPort    <util.js:1043:20>
    at TCPConnectWrap.afterConnect   [as oncomplete] <net.js:1090:14>


Im new to ionic 
 please help me

**Comment by dwieeb** [comment]
@ragul13 Please carefully follow the instructions for setting up a proxy: https://ionicframework.com/docs/cli/configuring.html#using-a-proxy
