### ISSUE TITLE
hooks doesn't have execute permissions in start project

### ISSUE THREAD

**Issue by leonprou** [driftyco/ionic-cli#351]
I started new ionic sidemenu project and added iOS platform to it. Then I tried to emulate it but got the following exception:

> Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at Object.exports.spawn (child_process.js:988:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:100:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:131:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:114:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)

Giving execute permissions to the hook solved this issue.

ionic-cli: 1.3.19
OS-X: 10.10.2

**Comment by cyprusglobe** [comment]
I'm seeing the same issue

ionic-cli: 1.3.19
OS-X: 10.10.2

**Comment by jbavari** [comment]
This will be fixed in the next release.

In the meantime, please run this in your Ionic's app directory:

`chmod -R 755 hooks/`

**Comment by jbavari** [comment]
This should be fixed in 1.3.21. Thanks

**Comment by 1hemant** [comment]
I have updated it but still getting this issue.


root@Hemants-Mac-mini/usr/local/myFirstIonicApp $ chmod -R 777 hooks/
root@Hemants-Mac-mini/usr/local/myFirstIonicApp $ exit
exit
hrathore@Netlinks-Mac-mini/usr/local/myFirstIonicApp $ ionic platform add ios
Updated the hooks directory to have execute permissions
/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/Users/hrathore/.config/configstore/update-notifier-cordova.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:27:44)
    at new UpdateNotifier (/usr/local/lib/node_modules/cordova/node_modules/update-notifier/index.js:34:17)
    at module.exports (/usr/local/lib/node_modules/cordova/node_modules/update-notifier/index.js:123:23)
    at checkForUpdates (/usr/local/lib/node_modules/cordova/src/cli.js:64:20)
    at cli (/usr/local/lib/node_modules/cordova/src/cli.js:114:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/bin/cordova:41:1)

**Comment by yokeshvaradhan** [comment]
hi
i am trying to clone a repo i clone it when i run it using ionic serve i get err like this
GET http://192.168.1.2:8100/lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js 
(index):53
 GET http://192.168.1.2:8100/lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js 404 (Not Found)

 i tryed this bower install ionic-platform-web-client and i get another err


/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/yokesh/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
yokeshs-Mac-mini:so-po-rockwell-app yokesh$
