### ISSUE TITLE
bug: ionic go down when receive a 302 reponse on proxy

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#374]
_From @jmaquet on April 7, 2015 7:58_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Ionic 1.3.16 on Ubuntu 14.04

I created a proxy in ionic.project to test a connexion webservice :
"proxies": [
      {
        "path": "/ws/connect",
        "proxyUrl": "http://xxx/api/v1/user"
      }
    ]

I'm using "ionic serve" to test.

Systematically when i receive a 302 code (found) from the webservice, my ionic server shut down and i receive the following response :
POST http://localhost:8100/ws/connect net::ERR_CONNECTION_REFUSED
2livereload.js?snipver=1:191 WebSocket connection to 'ws://localhost:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I have to restart my ionic server manually. For all the other codes : 200, 201, 403, 405, 404, 500 i have no issue.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3477_

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by prashantpalikhe** [comment]
Why was this issue considered to be resolved? Still facing the same issue here. 

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v8.9.1
    npm               : 5.5.1
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Misc:

    backend : legacy
