### ISSUE TITLE
npm install -g ionic failed

### ISSUE THREAD

**Issue by RobertLibe** [driftyco/ionic-cli#445]
Our proxy is blocking https://registry.npmjs.org/archiver/-/archiver-0.5.1.tgz as malware.
There are no problems with versions higher than 0.9.x.
Is it possible to change the archiver version manually?
Are there any issues for using the newer versions of archiver?

Thank you.

**Comment by jbavari** [comment]
@RobertLibe Theres no specific reason. I'm looking at updating it now. Stay posted.

**Comment by CoderNumber1** [comment]
We're having the same problem with https://registry.npmjs.org/archiver/-/archiver-0.5.1.tgz being blocked by our proxy for being detected as malware. Is there any known work around so ionic can be installed in the meantime?

**Comment by smokinguns** [comment]
@jbavari we are also having the same problem. Unfortunate timing i guess, because we are wanting to kick of a project, but can't get the tools downloaded on some developers machines. Any thoughts on when this might be cleared up?

**Comment by jbavari** [comment]
@smokinguns @CoderNumber1 @RobertLibe 

I'm pushing out a beta with some fixes.

Mind seeing if that will install? `npm install -g ionic@beta`.

**Comment by CoderNumber1** [comment]
@jbavari It looks like it's still trying to retrieve the 0.5.1 version of archiver as a dependency from https://registry.npmjs.org/archiver/-/archiver-0.5.1.tgz. Thanks for continuing to take a look at this for us.

**Comment by jbavari** [comment]
@CoderNumber1 

Whoops. I see what I did wrong. Derpppppp.

Fixed and published.

Try again please,
`npm install -g ionic@beta`

**Comment by RobertLibe** [comment]
@jbavari : Still the same problem:

    npm install -g ionic@beta
    ...
    npm http 403 https://registry.npmjs.org/archiver/-/archiver-0.5.1.tgz
    npm ERR! Error: 403 Forbidden

Thank you for trying =)

**Comment by jbavari** [comment]
@RobertLibe 

Just updated again. I'm testing again myself on another machine.

`npm install -g ionic@beta`

**Comment by RobertLibe** [comment]
Thank you for solving. No problems anymore!

**Comment by CoderNumber1** [comment]
:+1: Seems to be working now for me as well. Thanks again!

**Comment by jbavari** [comment]
@RobertLibe We've identified an issue with versions of archiver greater than 0.5.1  that cause issues for Android devices to un-zip the files compressed.

In the meantime, we will bump back to 0.5.1 (without the resolved url).

Please notify us if it becomes a problem.
