### ISSUE TITLE
Ionic Resources - produces icons/splash with wrong colors, from AI

### ISSUE THREAD

**Issue by jonalling** [driftyco/ionic-cli#604]
Ionic Resources produces icons and splash pages with the wrong colors when importing from an AI file.  

AI file:
![icon_intended-01](https://cloud.githubusercontent.com/assets/10489279/10283268/853d8d6e-6b44-11e5-81c7-fa1d9180be33.png)

Resulting png:
![icon_using resources](https://cloud.githubusercontent.com/assets/10489279/10283157/fadf62c8-6b43-11e5-8729-898ef7c533a8.png)

**Comment by GC-Mark** [comment]
Im getting a similar issue with PSD files as the source.

The background colour of my icon is `#000000` but after running through `ionic resources` the resulting icon background becomes `#2b3232`

Here is an example of the icon output (pain black background for demo purposes)
![icon-small 3x](https://cloud.githubusercontent.com/assets/1477806/11588527/3aa6914c-9a79-11e5-97c2-1c580ba8e83b.png)

Splash screens are fine though!

**Comment by GC-Mark** [comment]
Works fine if you save to `png` first, then generate

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by ish3lan** [comment]
The issue is still there
the result seems whitened 
please reopn

**Comment by carlosaiello** [comment]
yes @jthoms1 , this is still happening, I just exported a splash and the result is darker than the png that I used in the beginning.

**Comment by Gazaret** [comment]
i have this issue too

**Comment by supa-creation** [comment]
Change color mode to RVB work for me.

**Comment by whitecat** [comment]
How do I change color mode to RVB?
